GET http://localhost:3001/api/persons

###

DELETE https://intense-spire-96888.herokuapp.com/api/persons/6

###

POST https://intense-spire-96888.herokuapp.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "samplwe",
    "number": "123-456-789"
}